version: '3.9'

services:
  mongo:
    image: mongo:latest
    network_mode: host
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongodb_data:/data/db

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    network_mode: host
    environment:
      - MONGO_URL=mongodb://root:rootpassword@localhost:27017/
    depends_on:
      - mongo

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    network_mode: host
    depends_on:
      - server

volumes:
  mongodb_data: