# Dockerfile.server

# Build Stage
FROM golang:alpine AS builder

WORKDIR /app

# Copy go.mod and go.sum files to install dependencies first
COPY go.mod go.sum ./
RUN go mod download

# Copy the server source code
COPY ./server ./server

# Build the server binary
RUN go build -o server ./server/main.go

# Final Stage
FROM alpine:latest

WORKDIR /app

# Copy the binary from the builder stage
COPY --from=builder /app/server .

EXPOSE 8080

CMD ["./main"]