version: '3.9'

services:
  mongo:
    image: mongo:latest
    network_mode: host
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongodb_data:/data/db

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    network_mode: host
    environment:
      - MONGO_URL=mongodb://root:rootpassword@localhost:27017/
    depends_on:
      - mongo
  tests:
    image: golang:1.22
    depends_on:
      - server
    stop_signal: SIGKILL
    stdin_open: true
    tty: true
    working_dir: $PWD
    volumes:
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock
    command: go test ./... -v
    
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    network_mode: host
    depends_on:
      - server

volumes:
  mongodb_data: